### ISSUE TITLE
Une tribune pour discuter?

### ISSUE THREAD

**Issue by ghost** [cpp-frug/cpp-frug.github.io#1]
Bonjour,

Ce serait intéressant d'avoir un espace de discussion comme https://linuxfr.org/board

Je peux héberger ça si vous voulez.

**Comment by olibre** [comment]
Salut @devnewton 
Je découvre tout juste ta proposition, elle tient toujours ?
J'étais en train de réfléchir à réutiliser le soft [ZesteDeSavoir](https://github.com/zestedesavoir/zds-site).
Ou plus simple, d'intégrer le site ZesteDeSavoir et de se fondre dans la masse...
Qu'en penses-tu ?

**Comment by aurelienrb** [comment]
Hello,
A une époque on avait parlé d'héberger un Discourse (un genre de Stackoverflow):
http://try.discourse.org/

C'est sexy mais ce genre de projets demande de la maintenance / administration. A savoir qui va s'occuper des mises à jour, backup, et de la pérennité dans le temps? De mon expérience perso c'est très chronophage. Mais tu peux toujours monter une espace de démo pour qu'on se fasse une idée et voir si la sauce prend !

Pour ma part, après de nombreux essais / recherches de la solution magique qui allie outil sympa + pas cher à héberger + maintenance facile + passation de owner facile, je crois avoir enfin trouvé une formule sympa : 
- un site web statique rédigé en markdown et généré avec [Hugo](https://gohugo.io/)
- automatisation de la génération après commit / merge sur une branche dédiée dans le Github
- support des commentaires via... les commentaires Github : http://donw.io/post/github-comments/

Je suis prêt à travailler un peu à mettre ça en place pour le site principal sur Girhub: http://cpp-frug.github.io/

Aurélien

**Comment by olibre** [comment]
Moi aussi j'apprécie le côté mise à jour instantané avec HUGO, puis l'hébergement GitHub-pages (avec les aspects commit/merge de Git).

Par contre, je ne vois pas comment les commentaires GitHub peuvent être upvoted / downvoted...

Oui pour que tu y bosses un peu. Je pourrai te donner un coup de main dans 10 jours (je serai célibataire).

Jeudi soir, Meetup C++ à Paris. Dans la partie *Actualités C++FRUG*, je pourrais parler de tes expérimentations au cas où une personne du public serait prêt à nous donner un coup de main ;-)

**Comment by aurelienrb** [comment]
Ok, je vais essayer d'y consacrer un peu de temps pour mettre un prototype en place.

Pour les commentaires, oui c'est très basique... je pense que c'est satisfaisant pour réagir à des articles mais effectivement c'est pas idéal pour un forum de discussion 😞

**Comment by ghost** [comment]
@olibre  Oui, par contre j'ai l'impression qu'on parle de deux choses très différentes.

Pour moi, une tribune, c'est un chat web avec les norloges (comme https://linuxfr.org/board , http://sveetch.net/tribune/ ou chez moi https://b3.bci.im/).

ZesteDeSavoir ça a l'air d'être un site d'articles avec des commentaires.

**Comment by ghost** [comment]
J'ai deux moteurs de tribune: un complet en java (https://github.com/devnewton/jb3 démo: https://b3.bci.im) et un tout simple taab (php, démo: https://taab.bci.im/ ).

Si vous voulez quelque-chose de très simple, un site statique hugo+githubcomments comme suggéré pour la partie billets/commentaires et taab pour la partie discussion en live peut faire l'affaire.

**Comment by aurelienrb** [comment]
Ahhh... zavais pas compris moi non plus 😁 

Il me semble que ce qui est dans l'ère du temps c'est Slack... d'ailleurs y'a un espace C++ qui existe déjà:
https://isocpp.org/blog/2016/08/cpp-slack-group

Ici à Montpellier c'est très populaire pour fédérer les diverses communautés, et au boulot je m'essaye à l'utiliser.

L'avantage à une team FRUG sous Slack c'est qu'on peut y être connecté en permanence en même temps qu'on est présent sur Slack pour d'autres trucs. Et l'hébergement est gratuit pour un historique limité à 10.000 discussions.

**Comment by olibre** [comment]
Salut @devnewton 
J'ai été bluffé par ta tribune, ça mérite un étoile supplémentaire sur ton dépôt Git ;-)
J'ai même essayé la Visio :-) Par contre, comment gérer les nickname ? (j'ai eu du mal à trouver comment poster en tant que **olibre**) Est-ce que cppfrug.org peut rester un site web statique et avoir par exemple un sous domaine comme tribune.cppfrug.org qui utilise ton hébergement ?

Salut @aurelienrb 
Je ne connais pas bien Slack car jamais vraiment utilisé.
Au boulot on utilise plutôt IRC et [Mattermost](https://github.com/mattermost/platform/blob/master/README.md). Et nous avions aussi envisagé [Rocket.Chat](https://github.com/RocketChat/Rocket.Chat/blob/develop/README.md). Je n'ai pas cherché si ces alternatives sont proposés par des hébergeurs sympathiques. Qu'en penses-tu ?

**Comment by aurelienrb** [comment]
@olibre je connais Mattermost de nom, il a la réputation d'être une très bonne alternative à Slack. Mais il faut se gérer l'hébergement... qui va s'y coller? Un point autre important (pour ceux comme moi qui ne pensent pas à ouvrir constamment un onglet) : il dispose (comme Slack) de clients lourds desktop & mobile.

**Comment by olibre** [comment]
Le client lourd de Mattermost (sur Desktop) c'est exactement le même code source JavaScript et le même aspect que la page web. Je l'ai compilé moi même à partir de node.js. Le client lourd ne s'intègre pas plus dans l'environnement de bureau qu'un onglet d'un browser (pas de notification dans la tray icon). Je n'y ai trouvé aucun intérêt par rapport à un browser qui n'a qu'une seule page ouverte (une seule tabulation).

Du coup pour la présentation de ce soir, je vais parler de nos tergiversations :
http://cpp-frug.github.io/paris/events/2017-04-26_n17/news/reveal.html#/2

Bonne nuit ;-)

**Comment by ghost** [comment]
@olibre On peut faire un CNAME vers chez moi. Je le fais pour euromussels.eu => https://b3.euromussels.eu/?room=euromussels

**Comment by ghost** [comment]
Pour les autres systèmes de discussion semi instantanées:

- IRC n'a pas d'historique, c'est assez embêtant pour une communauté.
- slack n'est pas libre.
- seule les tribunes gèrent les norloges, peu de gens savent ce que sait, mais pour moi c'est indispensable pour une discussion de groupe :-)

**Comment by aurelienrb** [comment]
@olibre super, et tant qu'on y est peux-tu lancer un petit sondage sur qui serait à rejoindre le chat en fonction de quel outil on utilise?

@devnewton Slack n'est pas libre en effet, mais j'ai tendance à être très pragmatique pour ce genre de besoins : facilité de maintenance + popularité de l'outil me semblent important si on veut avoir une chance de créer une communauté en ligne. Je constate que par le passé, à chaque fois que dans un groupe on a rejeté une solution au motif que c'était pas libre / que c'était Google / Github, ben ça n'a rien donné ! 🤕

**Comment by olibre** [comment]
OK je ferai un sondage (j'ai tendance à faire des sondage à chaque slide). Je ferai aussi une mini-démo de github.com/devnewton/jb3 (avec gestion des norloges). Et je demanderai si des volontaires motivés veulent donner un coup de main...

**Comment by GuillaumeBelz** [comment]
Pourquoi pas un simple canal "fr" sur cpplang.slack.com ?

Je rejoins @aurelienrb, la maintenance est souvent un probleme critique sur le long terme, autant simplifier au maximum.

**Comment by ghost** [comment]
La classe ce serait une tribune en C++ pour montrer comment c'est surpuissant!

**Comment by olibre** [comment]
Associé au nom de domaine cppfrug.org, l'un de nous a aussi souscrit un hébergement web (je crois chez OVH). Avec cet hébergement minimaliste (10 Mo je crois...) il est possible d'avoir une lib qui gère le site web. Je crois me rappeler que c'est un module Apache. Donc effectivement, si l'un de nous est super motivé et qu'il code la tribune en C++ avec les API qui vont bien pour Apache, alors oui c'est faisable et cela ne coûte pas plus cher vis à vis de OVH (pas besoin de prendre une machine dédié). Et par la même occasion on enchaîne sur l'implémentation du forum, des journaux (...) des annonce de job (...) en C++ 😄

PS: ZesteDeSavoir est codé en Python (avec Django) et il existe quelques outils qui convertissent le Python en C++

**Comment by aurelienrb** [comment]
J'ai peur qu'on prouve plutôt que C++ n'est pas adapté au dev web 😁 De plus OVH fournit un [hébergement minimaliste](https://www.ovh.com/fr/domaines/offre_hebergement_start10m.xml) gratos avec ses noms de domaine mais c'est minimaliste et tu ne peux rien personnaliser à la stack software installée donc faut coder du CGI, c.à.d un programme en ligne de commande qui est invoqué par Apache... que tu auras uploadé en FTP... c'est très old school à l'heure des microservices livrés via Docker 😄 
C++ est utile dans les couches plus basses : serveur web, base de données, cache, interpréteur, etc...

---
Qui a accès à la gestion du nom de domaine sur OVH? Car il est possible de faire en sorte que ce soit Github qui fasse office d'hébergeur, mais faut [ajuster les paramètres du DNS](https://help.github.com/articles/setting-up-an-apex-domain/) côté OVH. *cpp-frug.github.io* s'afficherait alors avec l'url *cppfrug.org*

**Comment by olibre** [comment]
Bonjour @aurelienrb, @devnewton et @GuillaumeBelz. J'ai demandé au 35 présents ce qu'ils avaient envie d'utiliser pour se retrouver entre enthousiastes C++ francophones avec ce slide :
http://cpp-frug.github.io/paris/events/2017-05-18_n17/reveal.html#/2/2

J'ai listé les différentes propositions, mais peu d'enthousiasme, personne n'a vraiment voulu donné sa préférence, ou plutôt personne n'avait pu réfléchir en amont pour donner une réponse pertinente. J'ai enchaîné sur la démo de [jb3](https://github.com/devnewton/jb3) avec les **norloges** (concept que personne ne connaissait). Le public m'a semblé partant pour faire l'essai avec l'amical hébergement proposé par @devnewton.

Je vous propose d'essayer une instance [jb3](https://github.com/devnewton/jb3) configuré aux petits oignons par @devnewton au format complet (https://b3.bci.im) ou au format simple (https://taab.bci.im/) selon le feeling de @devnewton. Si cela ne prend pas alors, on pourra passer à un autre format... Qu'en pensez-vous ? @devnewton, es-tu est toujours partant ?

Il me semble que c'est @edouarda qui gère l'accès au nom de domaine. Et il se peut que @Klaim ait accès aussi au nom de domaine. Oui, ce serait bien que GitHub fasse office d'hébergeur avec cppfrug.org qui s'affiche à la place de cpp-frug.github.io 😄

**Comment by edouarda** [comment]
Oui j'ai accès au domaine. Dites moi ce que vous voulez modifier je le fais.

**Comment by ghost** [comment]
@olibre Toujours!

Il suffit de faire un cname vers chez moi, par exemple:

`tribune.cpp-frug.org.	10799	IN	CNAME	cpp-frug.bci.im.`

Je m'occuperais de vous créer ce qu'il faut derrière.

**Comment by olibre** [comment]
Salut @edouarda 

Je te propose de configurer le nom de domaine **`cppfrug.org`** pour pointer vers **`cpp-frug.github.io`** et vers **`cppfrug.bci.im`** avec quelque chose qui doit ressembler à cela :

    www  IN A    cpp-frug.github.io
    chat IN A    cppfrug.bci.im

De mémoire, le nom de domaine est chez OVH, c'est bien cela ?
La documentation de OVH est trop générale pour savoir comment faire pour notre cas :-/
https://docs.ovh.com/fr/fr/web/domains/editer-ma-zone-dns/#modification-de-votre-zone-dns

La documentation de GitHub n'explique pas ce qu'il faut faire chez OVH :
https://help.github.com/articles/quick-start-setting-up-a-custom-domain/
(cliquer sur *Setting up an apex domain and www subdomain such as example.com and www.example.com*)

Ne l'ayant jamais fait, je ne peux te dire comment faire. Et ce qui serait cool, c'est aussi d'avoir un truc comme cela :  

    ovh IN A    cppfrug.org
    *   IN A    cpp-frug.github.io

En parallèle, côté dépôt Git, il faut configurer correctement le CNAME :  
https://github.com/cpp-frug/cpp-frug.github.io/blob/master/CNAME.txt

Je laisse le soin aux experts @devnewton et @aurelienrb de prendre la main sur cette partie 😄 

Donc je propose un truc comme cela :  

         cppfrug.org   ->  cpp-frug.github.io
    chat.cppfrug.org   ->  cppfrug.bci.im
     ovh.cppfrug.org   ->  cppfrug.org
       *.cppfrug.org   ->  cpp-frug.github.io

La dernière ligne redirige alors **`www.cppfrug.org`** vers **`cpp-frug.github.io`**.

Vos suggestions, améliorations, remarques, contributions sont les bienvenues 😀

**Comment by edouarda** [comment]
J'ai ajoué le forward pour chat. http://www.cppfrug.org envoie déjà sur cpp-frug.github.io

**Comment by aurelienrb** [comment]
@edouarda cppfrug.org redirige en effet déjà sur cpp-frug.github.io, mais on souhaite faire mieux : au lieu de rediriger vers un autre nom de domaine, faire en sorte que ce soit toujours "cppfrug.org" qui s'affiche dans l'url au lieu de "cpp-frug.github.io", comme si nous hébergions nous même les pages sur OVH.
Il faut pour cela pointer vers l'IP de github et non son url. A priori c'est 192.30.252.153 et 192.30.252.154 :
https://help.github.com/articles/setting-up-an-apex-domain/
Normalement j'ai fait ce qu'il faut dans les settings de Github pour déclarer le domaine "cppfrug.org". Ainsi quand leur serveur web reçoit un routage depuis notre DNS au nom de "cppfrug.org", il devrait accepter d'afficher le contenu de cpp-frug.github.io mais donc avec l'url cppfrug.org

**Comment by Klaim** [comment]
Notez que http://cpp-frug.github.io/ mene a une erreur chez moi:
ERR_TOO_MANY_REDIRECTS

**Comment by ghost** [comment]
@edouarda tu peux faire un CNAME vers plutôt qu'un redirect http?

Si tu tiens vraiment à un redirect http, il faut rediriger vers https://b3.bci.im/?room=cppfrug

**Comment by edouarda** [comment]
Je m'en occupe cette semaine.

Sent from my iPhone

On May 24, 2017, at 11:52, devnewton <notifications@github.com<mailto:notifications@github.com>> wrote:


@edouarda<https://github.com/edouarda> tu peux faire un CNAME vers plutôt qu'un redirect http?

Si tu tiens vraiment à un redirect http, il faut rediriger vers https://b3.bci.im/?room=cppfrug

**Comment by edouarda** [comment]
J'ai fait le CNAME pour cppfrug.bci.im

En revanche il y a un problème pour http://cpp-frug.github.io/, je vais regarder.

**Comment by edouarda** [comment]
Il y a une redirection en place sur http://cpp-frug.github.io/ que j'aurais besoin que vous supprimiez le temps que fasse les changements DNS. thx.

**Comment by olibre** [comment]
Salut @edouarda 

Je viens juste de supprimer le contenu des fichiers CNAME et CNAME.txt
Tu as les droits d'écriture sur dépôt https://github.com/cpp-frug/cpp-frug.github.io dont n'hésite pas à modifier directement ces fichiers à ta convenance.

Si cela peut t'aider voici une explication succincte : 
https://gist.github.com/dineshsprabu/a09b1c8bc2a4646e49db

>1. Create a file CNAME on the gh-pages Branch.
> 
>2. Type your domain name and save the CNAME file. eg. dppages.com
> 
>3. Goto you domain settings on domain registered site (godaddy, bigrock, etc.,).
> 
>4. Add the IPs below on the 'A' record.
>    
>     192.30.252.153
>     192.30.252.154
> 
>Note: The above IPs are the github pages's DNS Server IPs.

**Comment by ghost** [comment]
@edouarda

Je me suis gouré comme un gros naze, le bon CNAME à faire c'est:

chat.cppfrug.org. 10799 IN CNAME b3.bci.im.

**Comment by edouarda** [comment]
J'ai fait les corrections, cela fonctionne. Il y a un problème de certificat sur le chat toutefois.

**Comment by ghost** [comment]
Voilà ça devrait être bon y compris pour le certificat: https://chat.cppfrug.org/

Dites moi si vous avez des idées pour améliorer l'ergonomie!

**Comment by olibre** [comment]
Trop bien, c'est trop classe 😃 
Vous avez bien bossé les gras  ;-)
J'ai rédigé un message sur meetup.com : 
https://www.meetup.com/fr-FR/User-Group-Cpp-Francophone/events/239663039/
À bientôt sur https://chat.cppfrug.org/ pour reprendre nos discussions ;)
